name: pasdf
channels:
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.11.0
  - torchvision=0.12.0
  - cudatoolkit=11.3
  - pytorch3d=0.7.4
  - pip:
      - -e .[dev]
