"""Prepare datasets and compute dataset statistics."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import yaml

from pcdad.data.dataset import (
    ALL_PCD_COLLECTIONS,
    DEFAULT_COLLECTIONS,
    AnomalyShapeNetDataset,
    DatasetStatistics,
    collect_dataset_statistics,
)
from pcdad.data.preprocess import NormalizationMode, prepare_pasdf_dataset
from pcdad.viz.pointcloud import write_pointcloud_gt_svg

DEFAULT_CONFIG = Path("configs/data/anomaly_shapenet.yaml")
DEFAULT_OUTPUT = Path("experiments/data_stats.md")
DEFAULT_PASDF_OUTPUT = Path("data/Anomaly-ShapeNet-v2/dataset/16384")
DEFAULT_SMOKE_OUTPUT = Path("experiments/p2_smoke/anomaly_shapenet_gt_normals.svg")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stat", action="store_true", help="Compute dataset statistics.")
    parser.add_argument(
        "--prepare-pasdf",
        action="store_true",
        help="Create a PASDF-compatible fixed-size dataset under dataset/16384.",
    )
    parser.add_argument(
        "--smoke-visualize",
        action="store_true",
        help="Write a point-cloud + GT + normal smoke SVG for one real sample.",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help=f"Dataset config used to resolve the default root. Default: {DEFAULT_CONFIG}",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Anomaly-ShapeNet root. Overrides dataset.root in --config.",
    )
    parser.add_argument(
        "--collections",
        nargs="+",
        default=None,
        choices=ALL_PCD_COLLECTIONS,
        help="PCD collections to summarize. Default: value from config or pcd.",
    )
    parser.add_argument(
        "--classes",
        nargs="+",
        default=None,
        help="Optional class filter for PASDF preparation or smoke visualization.",
    )
    parser.add_argument(
        "--all-collections",
        action="store_true",
        help="Summarize both official pcd and extension new_pcd collections.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Markdown report path. Default: {DEFAULT_OUTPUT}",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=DEFAULT_PASDF_OUTPUT,
        help=f"PASDF fixed-size dataset output root. Default: {DEFAULT_PASDF_OUTPUT}",
    )
    parser.add_argument(
        "--target-num-points",
        type=int,
        default=16384,
        help="Target point count for PASDF fixed-size samples.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Deterministic sampling seed.",
    )
    parser.add_argument(
        "--normalize",
        choices=[mode.value for mode in NormalizationMode],
        default=NormalizationMode.NONE.value,
        help="Normalization mode for PASDF fixed-size samples. Default keeps source scale.",
    )
    parser.add_argument(
        "--max-points",
        type=int,
        default=4096,
        help="Maximum points rendered in smoke visualization SVG.",
    )
    return parser.parse_args()


def _load_config(path: Path) -> dict:
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _dataset_config(config: dict) -> dict:
    value = config.get("dataset", {})
    return value if isinstance(value, dict) else {}


def _resolve_root(args: argparse.Namespace, dataset_config: dict) -> Path:
    if args.root is not None:
        return args.root
    configured_root = dataset_config.get("root")
    if configured_root is None:
        raise SystemExit("Dataset root is not configured. Pass --root or set dataset.root.")
    return Path(configured_root)


def _resolve_collections(args: argparse.Namespace, dataset_config: dict) -> tuple[str, ...]:
    if args.all_collections:
        return ALL_PCD_COLLECTIONS
    if args.collections is not None:
        return tuple(args.collections)
    configured = dataset_config.get("collections")
    if configured is None:
        return DEFAULT_COLLECTIONS
    if isinstance(configured, str):
        return (configured,)
    return tuple(configured)


def _format_counts(counts: dict[str, int]) -> str:
    if not counts:
        return "_none_"
    return "\n".join(f"- `{key}`: {value}" for key, value in counts.items())


def _render_report(stats: DatasetStatistics) -> str:
    point_counts = stats.point_counts
    ratio_percent = stats.aggregate_anomaly_ratio * 100.0
    lines = [
        "# Anomaly-ShapeNet Data Statistics",
        "",
        "Generated by `scripts/prepare_data.py --stat`.",
        "",
        "## Scope",
        "",
        f"- Root: `{stats.root}`",
        f"- Collections: `{', '.join(stats.collections)}`",
        f"- Classes: {stats.class_count}",
        f"- Samples: {stats.sample_count}",
        f"- GT files: {stats.gt_file_count}",
        "",
        "## Dataset Counts",
        "",
        "### Splits",
        "",
        _format_counts(stats.split_counts),
        "",
        "### Collections",
        "",
        _format_counts(stats.collection_counts),
        "",
        "### Sample Types",
        "",
        _format_counts(stats.anomaly_type_counts),
        "",
        "## Point Count Distribution",
        "",
        f"- Counted PCD files: {point_counts.count}",
        f"- Min points: {point_counts.min}",
        f"- Mean points: {point_counts.mean:.2f}",
        f"- Max points: {point_counts.max}",
        "",
        "## Point-Level GT Anomaly Ratio",
        "",
        f"- Labeled points: {stats.aggregate_labeled_points}",
        f"- Anomaly points: {stats.aggregate_anomaly_points}",
        f"- Aggregate anomaly ratio: {ratio_percent:.4f}%",
        "",
        "## Course Data Point-Count Check",
        "",
    ]
    if point_counts.max <= 30000:
        lines.append(
            "The observed PCD point counts match the public low-density Anomaly-ShapeNet "
            "range of roughly 8K-30K only if all samples fall under that ceiling."
        )
    else:
        lines.append(
            "The observed PCD point counts exceed the public 8K-30K description and align "
            "with a higher-density course package. Use downsampling before PASDF evaluation."
        )
    lines.extend(
        [
            "",
            "## Per-Class Summary",
            "",
            "| Class | Samples | Train | Test | Anomaly | Normal | Min Points | "
            "Mean Points | Max Points |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for class_name, class_stats in stats.class_stats.items():
        summary = class_stats.point_counts
        lines.append(
            f"| {class_name} | {class_stats.sample_count} | {class_stats.train_count} | "
            f"{class_stats.test_count} | {class_stats.anomaly_count} | "
            f"{class_stats.normal_count} | {summary.min} | {summary.mean:.2f} | {summary.max} |"
        )
    lines.append("")
    return "\n".join(lines)


def _estimate_normals_for_smoke(points: np.ndarray) -> np.ndarray | None:
    try:
        import open3d as o3d
    except ImportError:
        return None

    point_cloud = o3d.geometry.PointCloud()
    point_cloud.points = o3d.utility.Vector3dVector(points.astype("float64", copy=False))
    point_cloud.estimate_normals(
        search_param=o3d.geometry.KDTreeSearchParamKNN(knn=32),
    )
    return np.asarray(point_cloud.normals, dtype=np.float32)


def _write_smoke_visualization(
    *,
    root: Path,
    collections: tuple[str, ...],
    class_names: list[str] | None,
    output: Path,
    max_points: int,
    seed: int,
) -> None:
    dataset = AnomalyShapeNetDataset(root, split="test", collections=collections)
    for index in range(len(dataset)):
        points, _normals, labels, meta = dataset[index]
        if not meta["is_anomaly"]:
            continue
        if class_names is not None and meta["class_name"] not in class_names:
            continue
        title = (
            f"{meta['class_name']} / {meta['sample_id']} "
            f"({meta['anomaly_type']}, points={points.shape[0]}, anomalies={int(labels.sum())})"
        )
        write_pointcloud_gt_svg(
            output,
            points,
            labels,
            normals=_estimate_normals_for_smoke(points),
            title=title,
            max_points=max_points,
            seed=seed,
        )
        print(f"Wrote smoke visualization to {output}")
        print(f"sample={meta['sample_id']} class={meta['class_name']} points={points.shape[0]}")
        return
    raise SystemExit("No anomaly sample with GT matched the requested smoke visualization filters.")


def main() -> None:
    args = parse_args()
    config = _load_config(args.config)
    dataset_config = _dataset_config(config)
    root = _resolve_root(args, dataset_config)
    collections = _resolve_collections(args, dataset_config)
    if args.stat:
        stats = collect_dataset_statistics(root, collections=collections)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(_render_report(stats), encoding="utf-8")
        print(f"Wrote dataset statistics to {args.output}")
        print(
            f"samples={stats.sample_count} classes={stats.class_count} "
            f"points_min={stats.point_counts.min} points_mean={stats.point_counts.mean:.2f} "
            f"points_max={stats.point_counts.max} "
            f"anomaly_ratio={stats.aggregate_anomaly_ratio:.6f}"
        )
        return
    if args.prepare_pasdf:
        manifest = prepare_pasdf_dataset(
            root,
            output_root=args.output_root,
            target_num_points=args.target_num_points,
            seed=args.seed,
            collections=collections,
            class_names=args.classes,
            normalize=args.normalize,
        )
        print(
            f"Wrote PASDF dataset to {manifest.output_root} "
            f"samples={manifest.sample_count} target_num_points={manifest.target_num_points}"
        )
        return
    if args.smoke_visualize:
        _write_smoke_visualization(
            root=root,
            collections=collections,
            class_names=args.classes,
            output=args.output if args.output != DEFAULT_OUTPUT else DEFAULT_SMOKE_OUTPUT,
            max_points=args.max_points,
            seed=args.seed,
        )
        return
    raise SystemExit("No action requested. Use --stat, --prepare-pasdf, or --smoke-visualize.")


if __name__ == "__main__":
    main()
