"""Prepare datasets and compute dataset statistics."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml
from pcdad.data.dataset import (
    ALL_PCD_COLLECTIONS,
    DEFAULT_COLLECTIONS,
    DatasetStatistics,
    collect_dataset_statistics,
)

DEFAULT_CONFIG = Path("configs/data/anomaly_shapenet.yaml")
DEFAULT_OUTPUT = Path("experiments/data_stats.md")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stat", action="store_true", help="Compute dataset statistics.")
    parser.add_argument(
        "--config",
        type=Path,
        default=DEFAULT_CONFIG,
        help=f"Dataset config used to resolve the default root. Default: {DEFAULT_CONFIG}",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=None,
        help="Anomaly-ShapeNet root. Overrides dataset.root in --config.",
    )
    parser.add_argument(
        "--collections",
        nargs="+",
        default=None,
        choices=ALL_PCD_COLLECTIONS,
        help="PCD collections to summarize. Default: value from config or pcd.",
    )
    parser.add_argument(
        "--all-collections",
        action="store_true",
        help="Summarize both official pcd and extension new_pcd collections.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Markdown report path. Default: {DEFAULT_OUTPUT}",
    )
    return parser.parse_args()


def _load_config(path: Path) -> dict:
    if not path.is_file():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _dataset_config(config: dict) -> dict:
    value = config.get("dataset", {})
    return value if isinstance(value, dict) else {}


def _resolve_root(args: argparse.Namespace, dataset_config: dict) -> Path:
    if args.root is not None:
        return args.root
    configured_root = dataset_config.get("root")
    if configured_root is None:
        raise SystemExit("Dataset root is not configured. Pass --root or set dataset.root.")
    return Path(configured_root)


def _resolve_collections(args: argparse.Namespace, dataset_config: dict) -> tuple[str, ...]:
    if args.all_collections:
        return ALL_PCD_COLLECTIONS
    if args.collections is not None:
        return tuple(args.collections)
    configured = dataset_config.get("collections")
    if configured is None:
        return DEFAULT_COLLECTIONS
    if isinstance(configured, str):
        return (configured,)
    return tuple(configured)


def _format_counts(counts: dict[str, int]) -> str:
    if not counts:
        return "_none_"
    return "\n".join(f"- `{key}`: {value}" for key, value in counts.items())


def _render_report(stats: DatasetStatistics) -> str:
    point_counts = stats.point_counts
    ratio_percent = stats.aggregate_anomaly_ratio * 100.0
    lines = [
        "# Anomaly-ShapeNet Data Statistics",
        "",
        "Generated by `scripts/prepare_data.py --stat`.",
        "",
        "## Scope",
        "",
        f"- Root: `{stats.root}`",
        f"- Collections: `{', '.join(stats.collections)}`",
        f"- Classes: {stats.class_count}",
        f"- Samples: {stats.sample_count}",
        f"- GT files: {stats.gt_file_count}",
        "",
        "## Dataset Counts",
        "",
        "### Splits",
        "",
        _format_counts(stats.split_counts),
        "",
        "### Collections",
        "",
        _format_counts(stats.collection_counts),
        "",
        "### Sample Types",
        "",
        _format_counts(stats.anomaly_type_counts),
        "",
        "## Point Count Distribution",
        "",
        f"- Counted PCD files: {point_counts.count}",
        f"- Min points: {point_counts.min}",
        f"- Mean points: {point_counts.mean:.2f}",
        f"- Max points: {point_counts.max}",
        "",
        "## Point-Level GT Anomaly Ratio",
        "",
        f"- Labeled points: {stats.aggregate_labeled_points}",
        f"- Anomaly points: {stats.aggregate_anomaly_points}",
        f"- Aggregate anomaly ratio: {ratio_percent:.4f}%",
        "",
        "## Course Data Point-Count Check",
        "",
    ]
    if point_counts.max <= 30000:
        lines.append(
            "The observed PCD point counts match the public low-density Anomaly-ShapeNet "
            "range of roughly 8K-30K only if all samples fall under that ceiling."
        )
    else:
        lines.append(
            "The observed PCD point counts exceed the public 8K-30K description and align "
            "with a higher-density course package. Use downsampling before PASDF evaluation."
        )
    lines.extend(
        [
            "",
            "## Per-Class Summary",
            "",
            "| Class | Samples | Train | Test | Anomaly | Normal | Min Points | "
            "Mean Points | Max Points |",
            "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
        ]
    )
    for class_name, class_stats in stats.class_stats.items():
        summary = class_stats.point_counts
        lines.append(
            f"| {class_name} | {class_stats.sample_count} | {class_stats.train_count} | "
            f"{class_stats.test_count} | {class_stats.anomaly_count} | "
            f"{class_stats.normal_count} | {summary.min} | {summary.mean:.2f} | {summary.max} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    if args.stat:
        config = _load_config(args.config)
        dataset_config = _dataset_config(config)
        root = _resolve_root(args, dataset_config)
        collections = _resolve_collections(args, dataset_config)
        stats = collect_dataset_statistics(root, collections=collections)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(_render_report(stats), encoding="utf-8")
        print(f"Wrote dataset statistics to {args.output}")
        print(
            f"samples={stats.sample_count} classes={stats.class_count} "
            f"points_min={stats.point_counts.min} points_mean={stats.point_counts.mean:.2f} "
            f"points_max={stats.point_counts.max} "
            f"anomaly_ratio={stats.aggregate_anomaly_ratio:.6f}"
        )
        return
    raise SystemExit("No action requested. Use --stat after P2 is implemented.")


if __name__ == "__main__":
    main()
